name: Fetch MMA News Feeds

on:
  schedule:
    # Mon-Fri: every 3 hours 7am-5pm EST
    - cron: '0 12,15,18,21,0,2 * * 1-5'
    # Sat: every hour 5pm-2am EST
    - cron: '0 22,23,0,1,2,3,4,5,6 * * 6'
    # Sun: every hour 9am-12pm EST
    - cron: '0 14,15,16,17 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-feeds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser python-dateutil

      - name: Fetch RSS feeds
        run: |
          python fetch_feeds.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update MMA news feeds
          file_pattern: docs/mma-news.json
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
